"""add itunes podcast table

Revision ID: 15ddff36f0bf
Revises: 7ef4e32726fa
Create Date: 2020-07-07 01:48:03.857001

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '15ddff36f0bf'
down_revision = '7ef4e32726fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itunes_list_podcast',
                    sa.Column('itunes_id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('category_page', sa.Integer(), nullable=False),
                    sa.Column('category_letter', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('itunes_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itunes_list_podcast')
    # ### end Alembic commands ###
