"""add initial tables

Revision ID: 185ae507c9bb
Revises: 
Create Date: 2020-07-07 01:09:13.184900

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '185ae507c9bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itunes_top_level_categories',
                    sa.Column('itunes_id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('link', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('itunes_id')
                    )
    op.create_table('scheduled_jobs',
                    sa.Column('type', sa.Enum('TOP_LEVEL_CATEGORIES', 'CATEGORY_LETTER', 'PODCAST_LOOKUP',
                                              name='scheduledjobtypes'), nullable=False),
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('meta', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('next_time_at', sa.DateTime(), nullable=True),
                    sa.Column('finished_at', sa.DateTime(), nullable=True),
                    sa.Column('last_success_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('type', 'id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_jobs')
    op.drop_table('itunes_top_level_categories')
    # ### end Alembic commands ###
