"""add feed data

Revision ID: 6880af511893
Revises: bb474b900459
Create Date: 2020-07-09 18:32:21.518125

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6880af511893'
down_revision = 'bb474b900459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_feed_data',
                    sa.Column('itunes_id', sa.String(), nullable=False),
                    sa.Column('feed', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('itunes_id')
                    )
    op.create_table('podcasts',
                    sa.Column('itunes_id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('link', sa.String(), nullable=True),
                    sa.Column('generator', sa.String(), nullable=True),
                    sa.Column('last_build_date', sa.DateTime(), nullable=True),
                    sa.Column('author', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('copyright', sa.String(), nullable=True),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('itunes_type', sa.String(), nullable=True),
                    sa.Column('category', sa.JSON(), nullable=True),
                    sa.Column('last_episode_release', sa.DateTime(), nullable=True),
                    sa.Column('episodes', sa.Integer(), nullable=False),
                    sa.Column('is_persian', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('itunes_id')
                    )
    op.create_index(op.f('ix_podcasts_is_persian'), 'podcasts', ['is_persian'], unique=False)
    op.create_index(op.f('ix_podcasts_language'), 'podcasts', ['language'], unique=False)
    op.create_index(op.f('ix_podcasts_last_build_date'), 'podcasts', ['last_build_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcasts_last_build_date'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_language'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_is_persian'), table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_table('podcast_feed_data')
    # ### end Alembic commands ###
