"""add category id

Revision ID: 6d0846dbcfad
Revises: 41fefd609fe0
Create Date: 2020-07-08 05:11:07.963063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0846dbcfad'
down_revision = '41fefd609fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itunes_list_podcast', sa.Column('itunes_category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'itunes_list_podcast', 'itunes_top_level_categories', ['itunes_category_id'], ['itunes_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itunes_list_podcast', type_='foreignkey')
    op.drop_column('itunes_list_podcast', 'itunes_category_id')
    # ### end Alembic commands ###
