"""add indices

Revision ID: bb474b900459
Revises: 6d0846dbcfad
Create Date: 2020-07-08 18:58:16.133540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb474b900459'
down_revision = '6d0846dbcfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scheduled_jobs_finished_at'), 'scheduled_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_next_time_at'), 'scheduled_jobs', ['next_time_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_next_time_at'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_finished_at'), table_name='scheduled_jobs')
    # ### end Alembic commands ###
