version: '3.4'
services:
  #  tor:
  #    image: dperson/torproxy
  #    ports:
  #      - 9050:9050
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#  selenum_hub:
#    image: selenium/hub:3.141.59-zirconium
#    ports:
#      - "4444:4444"
#  firefox:
#    image: selenium/node-firefox:3.141.59-zirconium
#    volumes:
#      - /dev/shm:/dev/shm
#    environment:
#      HUB_HOST: selenum_hub
#      HUB_PORT: 4444
#    depends_on:
#      - selenum_hub
#    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'